sync

diff --git a/.github/workflows/pr_check_supportlist.yaml b/.github/workflows/pr_check_supportlist.yaml
--- a/.github/workflows/pr_check_supportlist.yaml
+++ b/.github/workflows/pr_check_supportlist.yaml
@@ -1,3 +1,4 @@
+---
 name: "PR Update Support List"
 on:
   pull_request:
@@ -6,6 +7,7 @@ on:
       - 'application/qmodem/files/usr/share/qmodem/modem_support.json'
 env:
   TZ: Asia/Jakarta
+
 jobs:
   update_support_list:
     runs-on: ubuntu-latest
@@ -26,35 +28,35 @@ jobs:
         id: update_modem_support_list
         env:
           GH_TOKEN: ${{ github.token }}
-          run: |
-            cd pr_branch
-            is_json_invalid=0
-            python3 ./scripts/update_support_list.py temp_support_list ./application/qmodem/files/usr/share/qmodem/modem_support.json || is_json_invalid=1
-            if [ "$is_json_invalid" = "1" ]; then
-              echo "pr_close=1" >> $GITHUB_OUTPUT
-              echo "The JSON file is invalid, please check" >> pr_comment.txt
-              exit 0
-            fi
-                
-            # Compare with base branch support_list.md
-            is_diff=0
-            if ! diff ./temp_support_list.md ../base_branch/docs/support_list.md > /dev/null 2>&1; then
-              is_diff=1
-            fi
-                
-            # Generate pr_comment.txt for comment
-            echo '```' > ./pr_comment.txt
-            diff -u ./temp_support_list.md ../base_branch/docs/support_list.md >> ./pr_comment.txt || true
-            echo '```' >> ./pr_comment.txt
-            if [ "$is_diff" = "1" ]; then
-              echo "The support list has been updated, please check the changes" >> ./pr_comment.txt
-              echo "pr_close=0" >> $GITHUB_OUTPUT
-              echo "has_diff=1" >> $GITHUB_OUTPUT
-            else
-              echo "No changes in the support list" >> ./pr_comment.txt
-              echo "pr_close=0" >> $GITHUB_OUTPUT
-              echo "has_diff=0" >> $GITHUB_OUTPUT
-            fi
+        run: |
+          cd pr_branch
+          is_json_invalid=0
+          python3 ./scripts/update_support_list.py temp_support_list ./application/qmodem/files/usr/share/qmodem/modem_support.json || is_json_invalid=1
+          if [ "$is_json_invalid" = "1" ]; then
+            echo "pr_close=1" >> $GITHUB_OUTPUT
+            echo "The JSON file is invalid, please check" >> pr_comment.txt
+            exit 0
+          fi
+
+          # Compare with base branch support_list.md
+          is_diff=0
+          if ! diff ./temp_support_list.md ../base_branch/docs/support_list.md > /dev/null 2>&1; then
+            is_diff=1
+          fi
+
+          # Generate pr_comment.txt for comment
+          echo '```' > ./pr_comment.txt
+          diff -u ./temp_support_list.md ../base_branch/docs/support_list.md >> ./pr_comment.txt || true
+          echo '```' >> ./pr_comment.txt
+          if [ "$is_diff" = "1" ]; then
+            echo "The support list has been updated, please check the changes" >> ./pr_comment.txt
+            echo "pr_close=0" >> $GITHUB_OUTPUT
+            echo "has_diff=1" >> $GITHUB_OUTPUT
+          else
+            echo "No changes in the support list" >> ./pr_comment.txt
+            echo "pr_close=0" >> $GITHUB_OUTPUT
+            echo "has_diff=0" >> $GITHUB_OUTPUT
+          fi
 
       - name: Close PR if JSON Invalid
         if: steps.update_modem_support_list.outputs.pr_close == '1'
